import { defineEntity, p } from '@mikro-orm/core';
import { User } from '../../users/domain/user.entity';
import { entityIdV7 } from '../../shared/base.entity';
import { EGaiaQueryCategory } from './gaia-query-category.enum';
import { EGaiaQueryFeedback } from './gaia-query-feedback.enum';
import { EGaiaQueryInputMode } from './gaia-query-input-mode.enum';

const GaiaQuerySchema = defineEntity({
  name: 'GaiaQuery',
  tableName: 'gaia_queries',
  properties: {
    id: entityIdV7,
    user: () => p.manyToOne(User).deleteRule('cascade'),
    /** 'text' for typed messages, 'voice' for audio transcriptions (QW1.3+) */
    inputMode: p
      .enum(Object.values(EGaiaQueryInputMode))
      .default(EGaiaQueryInputMode.TEXT),
    /** Gemini-assigned category — filled asynchronously after the response is sent */
    category: p.enum(Object.values(EGaiaQueryCategory)).nullable(),
    /** Short free-text topic generated by Gemini (max 120 chars) */
    topic: p.string().length(120).nullable(),
    /** One-sentence summary of the user query (max 300 chars) */
    summary: p.string().length(300).nullable(),
    /** Explicit user feedback on the GaIA response */
    feedback: p.enum(Object.values(EGaiaQueryFeedback)).nullable(),
    feedbackAt: p.datetime().nullable(),
    createdAt: p.datetime().onCreate(() => new Date()),
  },
  indexes: [
    { properties: ['category'] },
    { properties: ['feedback'] },
    { properties: ['inputMode'] },
    { properties: ['user', 'createdAt'] },
  ],
});

export class GaiaQuery extends GaiaQuerySchema.class {}

GaiaQuerySchema.setClass(GaiaQuery);
